version: '3.8'
services:
  wish-tree:
    image: wish-tree:latest
    container_name: wish-tree
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - 7000:7000
    env_file:
      - '../../api/.env'
    environment:
      DB_HOST: host.docker.internal

  wish-tree-ui:
    image: nginx:latest
    container_name: wish-tree-ui
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile.nginx
    ports:
      - 4444:80
    depends_on:
      - wish-tree
